package assignment_3;

import java.awt.*;
import javax.swing.*;
public class Calculator {
	JFrame frame;
	JPanel displayPanel, grid;
	JLabel display;
	GridBagConstraints c;
	JButton btn0, btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btnC, btnA, btnS, btnM, btnD, btnE;
	Calculator() {
		makeCalculator();
	}
	public void makeCalculator() {
		frame = new JFrame("Calculator");
		frame.setBackground(Color.DARK_GRAY);
		frame.setVisible(true);
		frame.setSize(300, 200);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		grid = new JPanel(new GridBagLayout());
		grid.setBackground(Color.DARK_GRAY);
		frame.add(grid);
		c = new GridBagConstraints();
		
		display = new JLabel("0");
		displayPanel = new JPanel();
		displayPanel.add(display);
		frame.add(displayPanel, BorderLayout.NORTH);
		
		btn1 = new JButton("1");
		btn1.setBackground(Color.DARK_GRAY);
		btn1.setOpaque(true);
		c.gridx = 0;
		c.gridy = 2;
		grid.add(btn1, c);
		btn2 = new JButton("2");
		btn2.setBackground(Color.DARK_GRAY);
		btn2.setOpaque(true);
		c.gridx = 1;
		c.gridy = 2;
		grid.add(btn2, c);
		btn3 = new JButton("3");
		btn3.setBackground(Color.DARK_GRAY);
		btn3.setOpaque(true);
		c.gridx = 2;
		c.gridy = 2;
		grid.add(btn3, c);
		btn4 = new JButton("4");
		btn4.setBackground(Color.DARK_GRAY);
		btn4.setOpaque(true);
		c.gridx = 0;
		c.gridy = 1;
		grid.add(btn4, c);
		btn5 = new JButton("5");
		btn5.setBackground(Color.DARK_GRAY);
		btn5.setOpaque(true);
		c.gridx = 1;
		c.gridy = 1;
		grid.add(btn5, c);
		btn6 = new JButton("6");
		btn6.setBackground(Color.DARK_GRAY);
		btn6.setOpaque(true);
		c.gridx = 2;
		c.gridy = 1;
		grid.add(btn6, c);
		btn7 = new JButton("7");
		btn7.setBackground(Color.DARK_GRAY);
		btn7.setOpaque(true);
		c.gridx = 0;
		c.gridy = 0;
		grid.add(btn7, c);
		btn8 = new JButton("8");
		btn8.setBackground(Color.DARK_GRAY);
		btn8.setOpaque(true);
		c.gridx = 1;
		c.gridy = 0;
		grid.add(btn8, c);
		btn9 = new JButton("9");
		btn9.setBackground(Color.DARK_GRAY);
		btn9.setOpaque(true);
		c.gridx = 2;
		c.gridy = 0;
		grid.add(btn9, c);
		btn0 = new JButton("0");
		btn0.setBackground(Color.DARK_GRAY);
		btn0.setOpaque(true);
		c.gridx = 0;
		c.gridy = 3;
		grid.add(btn0, c);
		btnC = new JButton("C");
		btnC.setBackground(Color.DARK_GRAY);
		btnC.setOpaque(true);
		c.gridx = 1;
		c.gridy = 3;
		grid.add(btnC, c);
		btnA = new JButton("+");
		btnA.setBackground(Color.DARK_GRAY);
		btnA.setOpaque(true);
		c.gridx = 3;
		c.gridy = 3;
		grid.add(btnA, c);
		btnS = new JButton("-");
		btnS.setBackground(Color.DARK_GRAY);
		btnS.setOpaque(true);
		c.gridx = 3;
		c.gridy = 2;
		grid.add(btnS, c);
		btnM = new JButton("*");
		btnM.setBackground(Color.DARK_GRAY);
		btnM.setOpaque(true);
		c.gridx = 3;
		c.gridy = 1;
		grid.add(btnM, c);
		btnD = new JButton("/");
		btnD.setBackground(Color.DARK_GRAY);
		btnD.setOpaque(true);
		c.gridx = 3;
		c.gridy = 0;
		grid.add(btnD, c);
		btnE = new JButton("=");
		btnE.setBackground(Color.DARK_GRAY);
		btnE.setOpaque(true);
		c.gridx = 2;
		c.gridy = 3;
		grid.add(btnE, c);
	}
}
